{% set name = "gnuradio-osmosdr" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitea.osmocom.org/sdr/gr-osmosdr/archive/v{{ version }}.tar.gz
  sha256: 8995313795fe7f6fad8f59072067cbfd4dcdb3fa40c5374bdac2c2fb82ce8ab6
  patches:
    - 0001-apps-Fix-osmocom_fft-on-Windows-where-dev-null-doesn.patch
    - 0002-redpitaya-For-Windows-target-Vista-or-newer-for-wins.patch

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('gnuradio-osmosdr', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - patch  # [osx]
    - pkg-config  # [not win]
    # cross-compilation requirements
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - pybind11                            # [build_platform != target_platform]
  host:
    - gmp            # [linux]
    - gnuradio-core  # [not gnuradio_extra_pin]
    - gnuradio-core {{ gnuradio_extra_pin }}.*  # [gnuradio_extra_pin]
    - gnuradio-funcube  # [linux]
    - gnuradio-iqbalance
    - gnuradio-uhd
    - libairspy
    - libairspyhf
    - libbladerf
    - libboost-devel
    - libhackrf
    - libmirisdr
    # needed for gnuradio-iqbalance
    - libosmo-dsp
    - numpy
    - pip  # [win]
    - pybind11
    - python
    - rtl-sdr
    - six
    - soapysdr
    - uhd
    - volk
  run:
    - {{ pin_compatible('gnuradio-uhd', max_pin='x.x.x') }}
    - python

test:
  requires:
    - gnuradio-qtgui  # [not (ppc64le or arm64)]
    - xorg-libxrender  # [linux and not ppc64le]
  commands:
    # verify that apps can run
    - "DISPLAY=localhost:1.0 xvfb-run -a bash -c 'osmocom_fft --help'"  # [linux and not ppc64le]
    - osmocom_fft --help  # [not linux and not arm64]
    - osmocom_siggen_nogui --help

    # verify that (some) headers get installed
    - test -f $PREFIX/include/osmosdr/api.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\osmosdr\\api.h exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]

    # verify that GRC blocks get installed
    {% set blocks = ["osmosdr_sink", "osmosdr_source"] %}
    {% for block in blocks %}
    - test -f $PREFIX/share/gnuradio/grc/blocks/{{ block }}.block.yml  # [not win]
    - if not exist %PREFIX%\\Library\\share\\gnuradio\\grc\\blocks\\{{ block }}.block.yml exit 1  # [win]
    {% endfor %}
  imports:
    - osmosdr

about:
  home: https://osmocom.org/projects/gr-osmosdr/wiki
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: osmocom GNU Radio blocks
  description: |
    While primarily being developed for the OsmoSDR hardware, this package also
    supports a variety of hardware receivers through direct plugins and the SoapySDR
    plugin. If a direct plugin is not available in this build, you might be able to get
    support by installing the appropriate module for SoapySDR.
  doc_url: https://osmocom.org/projects/gr-osmosdr/wiki
  dev_url: https://github.com/osmocom/gr-osmosdr

extra:
  recipe-maintainers:
    - ryanvolz
